# Uncomment the next line to define a global platform for your project
 platform :ios, '11.1'

target 'IosTeste' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IosTeste
pod 'SwiftyFORM', '~> 1.5'
pod 'Firebase', '~> 4.6'
pod 'FirebaseAuth', '~> 4.3'
pod 'FirebaseStorage', '~> 2.0'
pod 'FirebaseDatabase', '~> 4.1'
pod 'FacebookLogin', '~> 0.3'
end
